FROM python:3.6-alpine
 ENV PYTHONUNBUFFERED 1
 RUN mkdir /code
 WORKDIR /code
 ADD requirements.txt /code/
 ADD . /code/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install ipython
RUN pip install redis
RUN pip install gunicorn